LogLevel '4'
ListenUDP '0.0.0.0:1813'
ListenUDP '0.0.0.0:1812'
tls 'tls0' {
    CACertificateFile '/certs/ca.pem'
    certificateFile '/certs/cert.pem'
    certificateKeyFile '/certs/key.pem'
}
client 'client' {
    host '0.0.0.0/0'
    type 'udp'
    secret 'mysecret'
}
server 'server0' {
    host 'radius-bf.wifi.hellohelium.com'
    port '2083'
    type 'tls'
    tls 'tls0'
    certificateNameCheck off
    statusServer on
}
realm '/.*\.premnet\.wefi\.com$/' {
    server 'server0'
    accountingServer 'server0'
}
realm '/.*\.hellohelium\.com$/' {
    server 'server0'
    accountingServer 'server0'
}
realm 'wlan.mnc410.mcc310.3gppnetwork.org' {
    server 'server0'
    accountingServer 'server0'
}
realm 'wlan.mnc280.mcc310.3gppnetwork.org' {
    server 'server0'
    accountingServer 'server0'
}
realm 'wlan.mnc150.mcc310.3gppnetwork.org' {
    server 'server0'
    accountingServer 'server0'
}
realm 'wlan.mnc100.mcc313.3gppnetwork.org' {
    server 'server0'
    accountingServer 'server0'
}
realm 'wlan.mnc260.mcc310.3gppnetwork.org' {
    server 'server0'
    accountingServer 'server0'
}
realm 'wlan.mnc530.mcc312.3gppnetwork.org' {
    server 'server0'
    accountingServer 'server0'
}
realm 'wlan.mnc120.mcc310.3gppnetwork.org' {
    server 'server0'
    accountingServer 'server0'
}
realm 'wlan.mnc240.mcc310.3gppnetwork.org' {
    server 'server0'
    accountingServer 'server0'
}
realm * {
	replymessage "User unknown"
}
