home_server local_radsec_proxy_auth {
    type = auth
    ipaddr = radsecproxy
    port = 1812
    secret = "mysecret"
    response_window = 20
    zombie_period = 40
    revive_interval = 120
    status_check = status-server
}


home_server local_radsec_proxy_acct {
    type = acct
    ipaddr = radsecproxy
    port = 1813
    secret = "mysecret"
    response_window = 20
    zombie_period = 40
    revive_interval = 120
    status_check = status-server
}


home_server_pool local_radsec_proxy_auth_pool {
    type = fail-over
    home_server = local_radsec_proxy_auth
}


home_server_pool local_radsec_proxy_acct_pool {
    type = fail-over
    home_server = local_radsec_proxy_acct
}


realm DEFAULT {
    auth_pool = local_radsec_proxy_auth_pool
    acct_pool = local_radsec_proxy_acct_pool
    nostrip
}
